### ISSUE TITLE
Link to spec that is no longer compatible with this library

### ISSUE THREAD

**Issue by honungsburk** [Sphereon-Opensource/OpenID4VCI-client#19]
Hello! It seems like the specification that is linked to in the README has gone through a number of breaking changes and is no longer compatible with this version of the library. 
For example, the "issuance initiation endpoint" has been renamed to the "Credential Offer Endpoint" , and there are also a number of changes in the JSON. I wasn't able to find the version of the spec you guys were using and wondered if you had a link.

[Updated Spec](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-offer-endpoint)

**Comment by honungsburk** [comment]
Found an old version using the wayback machine

https://web.archive.org/web/20220626195129/https://openid.bitbucket.io/connect/openid-4-verifiable-credential-issuance-1_0.html#name-issuance-initiation-endpoin

**Comment by nklomp** [comment]
Hi @honungsburk Thanks for pointing it out. Yeah the versioning of the OpenID specs is a bit cumbersome, especially since they are constantly evolving and older versions are not linked.
We actually implemented version 09. We will have to look whether version 10 will be the next one we do and implement version discovery, or whether we will wait for a next implementers draft.

The diff between 09 and current (10) is mainly in renaming the endpoint. Reason why we will keep support for v09 is that multiple parties have shown interop with that version as part of the JFF plugfest a few months ago.

09 is roughly: https://bitbucket.org/openid/connect/commits/04652a78d55dab0e27cafaf1452de83d7be42e56

**Comment by honungsburk** [comment]
Thanks for the link!

**Comment by honungsburk** [comment]
I just realized that if you append the version number to the URL you will get the desired version of the spec.

latest: https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html

09: https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-09.html
08: https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-08.html
...

**Comment by nklomp** [comment]
Yeah, thanks I am aware of that. But for whatever reason the 09 link didn't work yesterday. Probably because the links have changed again recently
